set nocompatible " Disable compatibility with vi which can cause unexpected issues.
set foldmethod=syntax
set foldlevel=99
set backspace=indent,eol,start
set shiftwidth=2
set tabstop=2
set encoding=utf8
set number
set updatetime=300
set directory^=$HOME/.vim/tmp// "to organise swp files"

syntax enable " Turn syntax highlighting on.

filetype on " Enable type file detection. Vim will be able to try to detect the type of file in use.
filetype plugin on " Enable plugins and load plugin for the detected file type.
filetype indent on " Load an indent file for the detected file type.

let NERDTreeShowHidden=1
let g:NERDTreeWinPos = "right"

" Exit Vim if NERDTree is the only window remaining in the only tab.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif

" Open the existing NERDTree on each new tab.
" autocmd BufWinEnter * if getcmdwintype() == '' | silent NERDTreeMirror | endif

" If another buffer tries to replace NERDTree, put it in the other window, and bring back NERDTree.
autocmd BufEnter * if bufname('#') =~ 'NERD_tree_\d\+' && bufname('%') !~ 'NERD_tree_\d\+' && winnr('$') > 1 |
    \ let buf=bufnr() | buffer# | execute "normal! \<C-W>w" | execute 'buffer'.buf | endif

" PLUGINS ----------------------------------------------------------------
call plug#begin('~/.vim/plugged')
	Plug 'preservim/nerdtree'
	Plug 'preservim/nerdcommenter'
  Plug 'ryanoasis/vim-devicons'
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'
  Plug 'pangloss/vim-javascript'    " JavaScript support
  Plug 'maxmellon/vim-jsx-pretty'   " JS and JSX syntax
  Plug 'jparise/vim-graphql'        " GraphQL syntax
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
	Plug 'elixir-editors/vim-elixir' " Elixir support
	Plug 'prisma/vim-prisma' " Prisma support
	Plug 'airblade/vim-gitgutter' " Git Support
	Plug 'neoclide/jsonc.vim' "JSON formatting
	Plug 'tmsvg/pear-tree' " opening/closing brackets
	Plug 'tpope/vim-fugitive'
	Plug 'tpope/vim-surround'
  Plug 'easymotion/vim-easymotion'
	Plug 'vim-airline/vim-airline'
	Plug 'vim-airline/vim-airline-themes'

	Plug 'vim-ruby/vim-ruby'
	Plug 'rust-lang/rust.vim'
	Plug 'christoomey/vim-tmux-navigator'

	" Themes
	Plug 'arcticicestudio/nord-vim'
	Plug 'junegunn/seoul256.vim'
call plug#end()


if !has('gui_running') && &term =~ '^\%(screen\|tmux\)'
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif


"Color Scheme
if (has("termguicolors"))
	set termguicolors
endif

set background=dark
" "colorscheme nord
" highlight Comment ctermfg=darkgray
let g:seoul256_background = 235
let g:airline_theme='zenburn'

colo seoul256

" MAPPINGS --------------------------------------------------------------- {{{

" Type jj to exit insert mode quickly.
inoremap jj <Esc>

" Use arrow keys to resize windows
nnoremap <Up>    :resize -2<CR>
nnoremap <Down>  :resize +2<CR>
nnoremap <Left>  :vertical resize -2<CR>
nnoremap <Right> :vertical resize +2<CR>

" NERDTree specific mappings.
map <silent> <C-n> :NERDTreeToggle<CR>
map <leader>r :NERDTreeFind<cr>

nmap <C-P> :FZF<CR>
nnoremap <silent> <C-f> :Ag<CR>
nnoremap <silent> <expr> <Leader><Leader> (expand('%') =~ 'NERD_tree' ? "\<c-w>\<c-w>" : '').":FZF\<cr>"

" CoC extensions
let g:coc_global_extensions = ['coc-tsserver', 'coc-json', 'coc-eslint', 'coc-css', 'coc-prettier', 'coc-elixir', 'coc-prisma', '@yaegassy/coc-tailwindcss3']

" Remap keys for applying codeAction to the current line.
nmap <leader>ac  <Plug>(coc-codeaction)

" Apply AutoFix to problem on the current line.
nmap <leader>qf  <Plug>(coc-fix-current)

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

nnoremap <silent> K :call ShowDocumentation()<CR>

function! ShowDocumentation()
	if CocAction('hasProvider', 'hover')
		call CocActionAsync('doHover')
	else
		call feedkeys('K', 'in')
	endif
endfunction

" Highlight the symbol and its references when holding the cursor
autocmd CursorHold * silent call CocActionAsync('highlight')

inoremap " ""<left>
inoremap ' ''<left>
inoremap ( ()<left>
inoremap [ []<left>
inoremap { {}<left>
inoremap {<CR> {<CR>}<ESC>O
inoremap {;<CR> {<CR>};<ESC>O

let g:rustfmt_autosave = 1
